### ISSUE TITLE
Benchmarks addition to readme

### ISSUE THREAD

**Issue by kishaningithub** [hamba/logger#42]
Thanks for creating this, i really love the API

I feel it would be great if you could add benchmark results to the readme.. Even better if you could add this library's benchmark tests here https://github.com/rs/logbench this runs benchmarks for several structured loggers and the stats is always upto date. 

Thanks in advance!

**Comment by kishaningithub** [comment]
Also the live results of logbench are always visible here :-) http://hackemist.com/logbench/

**Comment by nrwiersma** [comment]
I feel no need for benchmarks on the readme in this case. If you wish to add this lib to `logbench` feel free.
